# Generated by Django 4.2.20 on 2025-04-24 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generalManager',
            fields=[
                ('ManagerID', models.IntegerField(primary_key=True, serialize=False)),
                ('isManager', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemID', models.IntegerField(primary_key=True, serialize=False)),
                ('Stock', models.IntegerField()),
                ('Category', models.TextField(default=None)),
                ('itemName', models.TextField(default=None)),
                ('RetailPrice', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('StaffID', models.IntegerField(primary_key=True, serialize=False)),
                ('First Name', models.TextField(default=None)),
                ('Last Name', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('RequestID', models.IntegerField(primary_key=True, serialize=False)),
                ('Request Date', models.DateField()),
                ('Comments', models.TextField()),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wfdApp.item')),
                ('ManagerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wfdApp.generalmanager')),
                ('StaffID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wfdApp.staffmember')),
            ],
        ),
        migrations.AddField(
            model_name='generalmanager',
            name='foreName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generalManager-FirstName+', to='wfdApp.staffmember'),
        ),
        migrations.AddField(
            model_name='generalmanager',
            name='surName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generalManager-LastName+', to='wfdApp.staffmember'),
        ),
        migrations.CreateModel(
            name='ShiftManager',
            fields=[
                ('staffID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='staffID', serialize=False, to='wfdApp.staffmember')),
                ('hasManagerAction', models.BooleanField(default=False)),
                ('fName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shiftManager-FirstName+', to='wfdApp.staffmember')),
                ('lName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shiftManager-LastName+', to='wfdApp.staffmember')),
            ],
        ),
        migrations.CreateModel(
            name='newItemRequest',
            fields=[
                ('RequestID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='wfdApp.request')),
                ('Request Date', models.DateField()),
                ('Comments', models.TextField()),
                ('ManagerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wfdApp.generalmanager')),
                ('StaffID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wfdApp.staffmember')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='newitem-Category+', to='wfdApp.item')),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='newItem-ItemID+', to='wfdApp.item')),
            ],
        ),
        migrations.CreateModel(
            name='editRequest',
            fields=[
                ('RequestID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='wfdApp.request')),
                ('Request Date', models.DateField()),
                ('New Stock', models.IntegerField()),
                ('Comments', models.TextField()),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wfdApp.item')),
            ],
        ),
        migrations.CreateModel(
            name='deletionRequest',
            fields=[
                ('RequestID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='wfdApp.request')),
                ('Request Date', models.DateField()),
                ('Comments', models.TextField()),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfdApp.item')),
            ],
        ),
    ]
