# Generated by Django 4.2.20 on 2025-04-20 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfdApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalmanager',
            name='isManager',
        ),
        migrations.RemoveField(
            model_name='shiftmanager',
            name='hasManagerAction',
        ),
        migrations.AlterField(
            model_name='generalmanager',
            name='foreName',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.PROTECT, related_name='generalManager-FirstName+', to='wfdApp.staffmember'),
        ),
        migrations.AlterField(
            model_name='generalmanager',
            name='surName',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, related_name='generalManager-LastName+', to='wfdApp.staffmember'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Category',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='Description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='Comments',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shiftmanager',
            name='fName',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.PROTECT, related_name='shiftManager-FirstName+', to='wfdApp.staffmember'),
        ),
        migrations.AlterField(
            model_name='shiftmanager',
            name='lName',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, related_name='shiftManager-LastName+', to='wfdApp.staffmember'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='First Name',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='Last Name',
            field=models.TextField(max_length=20),
        ),
    ]
