# Generated by Django 4.2.20 on 2025-04-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfdApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='RetailPrice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='First Name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='Last Name',
            field=models.TextField(),
        ),
    ]
