# Generated by Django 4.2.20 on 2025-04-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfdApp', '0002_alter_item_category_alter_item_retailprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='First Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='Last Name',
            field=models.CharField(max_length=50),
        ),
    ]
