# Generated by Django 4.2.20 on 2025-04-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfdApp', '0002_remove_generalmanager_ismanager_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftmanager',
            options={'permissions': [('edit stock', 'can edit stock of items')]},
        ),
    ]
