# Generated by Django 4.2.20 on 2025-04-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfdApp', '0003_alter_shiftmanager_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='First Name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='Last Name',
            field=models.CharField(max_length=20),
        ),
    ]
