# Generated by Django 4.2.20 on 2025-04-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfdApp', '0003_alter_item_category_alter_item_itemname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itemName',
            new_name='ItemName',
        ),
        migrations.AlterField(
            model_name='item',
            name='RetailPrice',
            field=models.FloatField(),
        ),
    ]
