# Generated by Django 4.2.20 on 2025-04-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfdApp', '0004_alter_item_itemname_alter_staffmember_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='Description',
            field=models.CharField(max_length=100),
        ),
    ]
