# Generated by Django 4.2.20 on 2025-04-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfdApp', '0004_rename_itemname_item_itemname_alter_item_retailprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='RetailPrice',
            field=models.IntegerField(),
        ),
    ]
