# Generated by Django 4.2.20 on 2025-04-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfdApp', '0005_alter_item_category_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Retail Price',
            field=models.FloatField(),
        ),
    ]
