# Generated by Django 4.2.20 on 2025-04-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfdApp', '0005_alter_item_retailprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editrequest',
            name='ItemID',
        ),
        migrations.RemoveField(
            model_name='editrequest',
            name='RequestID',
        ),
        migrations.RemoveField(
            model_name='newitemrequest',
            name='ManagerID',
        ),
        migrations.RemoveField(
            model_name='newitemrequest',
            name='RequestID',
        ),
        migrations.RemoveField(
            model_name='newitemrequest',
            name='StaffID',
        ),
        migrations.RemoveField(
            model_name='newitemrequest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newitemrequest',
            name='itemID',
        ),
        migrations.AddField(
            model_name='request',
            name='New Stock',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='deletionRequest',
        ),
        migrations.DeleteModel(
            name='editRequest',
        ),
        migrations.DeleteModel(
            name='newItemRequest',
        ),
    ]
