# Generated by Django 4.2.20 on 2025-04-20 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfdApp', '0006_alter_item_retail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletionrequest',
            name='ItemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfdApp.item'),
        ),
        migrations.AlterField(
            model_name='deletionrequest',
            name='RequestID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wfdApp.request'),
        ),
        migrations.AlterField(
            model_name='editrequest',
            name='ItemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfdApp.item'),
        ),
        migrations.AlterField(
            model_name='editrequest',
            name='RequestID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wfdApp.request'),
        ),
        migrations.AlterField(
            model_name='generalmanager',
            name='foreName',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='generalManager-FirstName+', to='wfdApp.staffmember'),
        ),
        migrations.AlterField(
            model_name='generalmanager',
            name='surName',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='generalManager-LastName+', to='wfdApp.staffmember'),
        ),
        migrations.AlterField(
            model_name='newitemrequest',
            name='ManagerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfdApp.generalmanager'),
        ),
        migrations.AlterField(
            model_name='newitemrequest',
            name='RequestID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wfdApp.request'),
        ),
        migrations.AlterField(
            model_name='newitemrequest',
            name='StaffID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfdApp.staffmember'),
        ),
        migrations.AlterField(
            model_name='newitemrequest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newitem-Category+', to='wfdApp.item'),
        ),
        migrations.AlterField(
            model_name='newitemrequest',
            name='itemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newItem-ItemID+', to='wfdApp.item'),
        ),
        migrations.AlterField(
            model_name='request',
            name='ItemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfdApp.item'),
        ),
        migrations.AlterField(
            model_name='request',
            name='ManagerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfdApp.generalmanager'),
        ),
        migrations.AlterField(
            model_name='request',
            name='StaffID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfdApp.staffmember'),
        ),
        migrations.AlterField(
            model_name='shiftmanager',
            name='fName',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='shiftManager-FirstName+', to='wfdApp.staffmember'),
        ),
        migrations.AlterField(
            model_name='shiftmanager',
            name='lName',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='shiftManager-LastName+', to='wfdApp.staffmember'),
        ),
        migrations.AlterField(
            model_name='shiftmanager',
            name='staffID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='staffID', serialize=False, to='wfdApp.staffmember'),
        ),
    ]
