# Generated by Django 4.2.20 on 2025-04-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfdApp', '0007_alter_generalmanager_forename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='reqType',
            field=models.CharField(choices=[('DELETION', 'Deletion'), ('ADDITION', 'Addition'), ('EDITING', 'Editing')], default='Editing', max_length=20),
        ),
    ]
