# Generated by Django 4.2.20 on 2025-04-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfdApp', '0007_alter_deletionrequest_itemid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Retail Price',
            new_name='RetailPrice',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Stock',
            new_name='stock',
        ),
    ]
