# Generated by Django 4.2.20 on 2025-04-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfdApp', '0008_request_reqtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='ItemID',
            new_name='ItemName',
        ),
    ]
