# Generated by Django 4.2.20 on 2025-04-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfdApp', '0009_rename_itemid_request_itemname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='New Stock',
            new_name='NewStock',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Request Date',
            new_name='RequestDate',
        ),
    ]
