# Generated by Django 4.2.20 on 2025-04-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfdApp', '0010_rename_new_stock_request_newstock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='ManagerID',
        ),
        migrations.RemoveField(
            model_name='request',
            name='StaffID',
        ),
    ]
