# Generated by Django 4.2.20 on 2025-04-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfdApp', '0011_remove_request_managerid_remove_request_staffid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='ItemName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wfdApp.item'),
        ),
    ]
